service: assignment03

frameworkVersion: ">=1.1.0"

custom:
  bucket: wmdd4999-assignment03

provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  postprocess:
    handler: handler.postprocess
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .png

# resources:  // CloudFormation template syntax
Resources: 
  wmdd4999-assignment03:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: wmdd4999-assignment03
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1